ALTER TABLE `achievement_global_metrics` ADD `tasks_added` integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `achievement_global_metrics` ADD `tasks_abandoned` integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `achievement_global_metrics` ADD `tasks_deleted` integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `achievement_global_metrics` ADD `habits_added` integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `achievement_global_metrics` ADD `habits_with_weekly_goals` integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `achievement_global_metrics` ADD `habits_with_daily_goals` integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `achievement_global_metrics` ADD `habits_abandoned` integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `achievement_global_metrics` ADD `habit_goals_restarted` integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `achievement_global_metrics` ADD `habits_deleted` integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `achievement_global_metrics` ADD `events_added` integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `achievement_global_metrics` ADD `events_deleted` integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `achievement_global_metrics` ADD `events_earlymorning` integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `achievement_global_metrics` ADD `events_latenight` integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `achievement_global_metrics` ADD `events_overnight` integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `achievement_global_metrics` ADD `events_daily` integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `achievement_global_metrics` ADD `events_weekly` integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `achievement_global_metrics` ADD `events_singleton` integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `achievement_global_metrics` ADD `events_infinite` integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `daily_metrics` ADD `tasks_added` integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `daily_metrics` ADD `tasks_abandoned` integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `daily_metrics` ADD `tasks_missed` integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `daily_metrics` ADD `tasks_deleted` integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `daily_metrics` ADD `habits_added` integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `daily_metrics` ADD `habits_with_weekly_goals` integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `daily_metrics` ADD `habits_with_daily_goals` integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `daily_metrics` ADD `habits_abandoned` integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `daily_metrics` ADD `habit_goals_restarted` integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `daily_metrics` ADD `habit_check_ins_missed` integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `daily_metrics` ADD `habits_auto_frozen` integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `daily_metrics` ADD `habits_deleted` integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `daily_metrics` ADD `events_added` integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `daily_metrics` ADD `events_deleted` integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `daily_metrics` ADD `events_earlymorning` integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `daily_metrics` ADD `events_latenight` integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `daily_metrics` ADD `events_overnight` integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `daily_metrics` ADD `events_daily` integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `daily_metrics` ADD `events_weekly` integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `daily_metrics` ADD `events_singleton` integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `daily_metrics` ADD `events_infinite` integer DEFAULT 0 NOT NULL;