// Helper function to grab a random string from an array
export const getRandomProgressText = (options: string[]) => {
    return options[Math.floor(Math.random() * options.length)];
};

export const AgentPersona = {
    WAKING_UP: [
        "Initiating HyperDrive",
        "Brewing digital coffee",
        "Stretching neural networks",
        "Waking up the agent",
        "Creating the universe",
        "Engaging Thrusters",
        "Launching Missle",
        "Onboarding AI intern",
        "Casting Resurrection",
        "Igniting Lightsabers",
        "Calling the Fellowship",
        "Starting New Game+",
        "Assembling the Guardians",
        "Bringing the Matrix Online",
        "Awakening the Titans",
        "Downloading More RAM",
        "Opening the Portal",
        "Releasing the Kraken",
        "Charging Arc Reactor",
        "Waking the Force",
        "Opening the Stargate",

    ],
    PLANNING: [
        "Mapping the multiverse",
        "Drafting the master plan",
        "Connecting the dots",
        "Analyzing complex request",
        "Hiring Strategist",
        "Laying out the roadmap",
        "Doctor Strange-ing Futures",
        "Consulting the Oracle",
        "Running the Simulation",
        "Calculating 14,000,605 Outcomes",
        "Summoning Grand Strategy",
        "Consulting Gandalf",
        "Playing 4D Chess",
        "Building the Master Plan",
        "Reading the Ancient Texts",
        "Scanning the Timeline",
        "Analyzing the Sacred Timeline",
        "Computing Victory Conditions",
        "Searching for Side Quests",
        "Reviewing the Codex",
        "Unlocking the Skill Tree",
        "Predicting the Endgame",
        "Consulting the Holocron",
        "Examining the Infinity Stones"
    ],
    ROUTING: [
        "Choosing weapons",
        "Assembling the toolset",
        "Selecting the right tools",
        "Loading domain expertise",
        "Picking Warriors",
        "Setting the Modus Oprendi",
        "Equipping Loadout",
        "Choosing a Starter Pokémon",
        "Selecting the Infinity Stones",
        "Calling in Reinforcements",
        "Summoning the Avengers",
        "Recruiting the Fellowship",
        "Picking the Right Spell",
        "Equipping Legendary Gear",
        "Assigning Skill Points",
        "Choosing the Party",
        "Selecting Companion AI",
        "Gathering the Dragon Balls",
        "Opening the Armory",
        "Preparing the Batcave",
        "Deploying Strike Team",
        "Choosing the Right Portal",
        "Selecting Special Abilities",
        "Preparing Mission Control"
    ],
    EXECUTING: [
        "Executing Order 66",
        "Making It So",
        "Punching Through Reality",
        "Rolling for Initiative",
        "Going Super Saiyan",
        "Engaging Hyperdrive",
        "Casting Fireball",
        "Entering the Matrix",
        "Completing the Side Quest",
        "Activating Plot Armor",
        "Unleashing the Combo",
        "Speedrunning the Objective",
        "Pushing the Big Red Button",
        "Breaking the Fourth Wall",
        "Deploying Tactical Genius",
        "Channeling Main Character Energy",
        "Launching the Final Boss Fight",
        "Calling Upon the Power of Friendship"
    ],
    EVALUATING: [
        "Double-checking the math",
        "Checking the checklist",
        "Surveying the results",
        "Evaluating execution",
        "Reality Check",
        "Reading the Mission Report",
        "Checking the Lore",
        "Consulting the Archives",
        "Reviewing the Replay",
        "Checking the Patch Notes",
        "Analyzing Battle Damage",
        "Examining the Aftermath",
        "Verifying the Timeline",
        "Reviewing the Quest Log",
        "Checking the Kill Feed",
        "Inspecting the Evidence",
        "Reviewing Security Footage",
        "Consulting the Watcher",
        "Looking for Plot Holes",
        "Examining Alternate Timelines",
        "Checking the End Credits"
    ],
    // Specific Tool Actions
    ACTION_TASK: [
        "Forging a new task",
        "Writing it in stone",
        "Adding task to the docket",
        "Updating Captain's Log",
        "Adding to the to-do codex",
    ],
    ACTION_HABIT: [
        "Spraying in Consistency",
        "Wiring new routines",
        "Building good habits",
        "Forging daily rituals",
        "Building muscle memory",
        "Entering the Hyperbolic Time Chamber",
        "Teaching old dogs new tricks",
        "Laying another brick",
        "Planting the consistency seed",
        "Strengthening neural pathways",
        "Updating the routine matrix",
        "Unlocking passive skills",
        "Beginning the training montage",
        "Grinding XP",
    ],
    ACTION_CATEGORY: [
        "Organizing the chaos",
        "Painting categories",
        "Filing into folders",
        "Sorting the Infinity Stones",
        "Bringing balance to the Force",
        "Organizing the multiverse",
        "Restoring order to chaos",
        "Building the Hogwarts houses",
        "Creating a new faction",
        "Expanding the kingdom",
        "Founding a guild",
        "Creating another timeline",
        "Partitioning reality",
        "Color-coding the universe",
        "Building the archive",
        "Constructing the taxonomy",
        "Filing with the Time Variance Authority",
        "Dividing and conquering"
    ],
    ACTION_TAG: [
        "Slapping on tags",
        "Labeling things",
        "Pinning tags",
        "Applying tracking beacons",
        "Marking the target",
        "Attaching metadata",
        "Casting Identification",
        "Labeling evidence",
        "Tagging for future archaeology",
        "Leaving breadcrumbs",
        "Adding detective notes",
        "Teaching the archives",
        "Pinning the suspect board",
        "Indexing the timeline",
        "Naming the unnamed",
        "Marking it for retrieval",
        "Teaching the AI new vocabulary",
        "Adding searchable magic"
    ],
    ACTION_SEARCH: [
        "Scouring the database",
        "Hunting for context",
        "Flipping through archives",
        "Consulting the Jedi Archives",
        "Searching the ancient texts",
        "Scanning the multiverse",
        "Consulting the Oracle",
        "Summoning Sherlock Holmes",
        "Searching the Matrix",
        "Following the breadcrumbs",
        "Opening the restricted section",
        "Investigating the evidence board",
        "Searching alternate timelines",
        "Asking the Librarian",
        "Excavating the archives",
        "Rolling Investigation",
        "Tracking the One Ring",
        "Reading forbidden knowledge"
    ],
    ACTION_EVENT: [
        "Marking the sacred timeline",
        "Consulting the Time Stone",
        "Scheduling a canon event",
        "Adding a point in spacetime",
        "Writing history in advance",
        "Booking a meeting with destiny",
        "Updating the timeline",
        "Reserving a slot in the multiverse",
        "Adding to the prophecy",
        "Synchronizing with Mission Control",
        "Consulting Doctor Who",
        "Programming the TARDIS",
        "Creating a fixed point in time",
        "Scheduling the inevitable",
        "Blocking out spacetime",
        "Setting coordinates for the future",
        "Preparing the DeLorean",
        "Booking a temporal waypoint",
        "Registering with the TVA",
        "Plotting the next chapter"
    ]
};